# config.toml

title = "yokai_gate_config"

debug = true

# ip and port
gate_id = 2001
https_listen_addr = ":443"
default_game_id = "1001"

# tls_debug
cert_path_debug = "../../config/cert/localhost.crt"
key_path_debug = "../../config/cert/localhost.key"

# tls_release
cert_path_release = "../../config/cert/hellodudu.crt"
key_path_release = "../../config/cert/hellodudu.key"

# db
db_dsn = "mongodb://localhost:27017"
database = "db_gate"

# gate evironment
registry = "consul"
broker = "nsq"
