# config.toml

title = "yokai_gate_config"

debug = false

# ip and port
gate_id = 101
https_listen_addr = ":443"
http_listen_addr = ":80"
default_game_id = "301"

# tls config
cert_path_debug = "config/cert/localhost.crt"
key_path_debug = "config/cert/localhost.key"

cert_path_release = "config/cert/localhost.crt"
key_path_release = "config/cert/localhost.key"

# db
db_dsn = "mongodb://localhost:27017"
database = "db_gate"
redis_addr = "localhost:6379"

# gate evironment
registry_debug = "mdns"
broker_debug = "http"

registry_release = "consul"
broker_release = "nsq"
