# config.toml

title = "yokai_battle_config"

battle_id = 2001
db_dsn = "root:@(127.0.0.1:3306)/db_battle"
http_listen_addr = ":8081"

# battle evironment
registry = "mdns"
transport = "tcp"
broker = "http"
server_id = 2001
