# config.toml

title = "yokai_game_config"

game_id = 1001
account_connect_max = 5000

# ip and port
public_ip = "127.0.0.1"
http_listen_addr = ":8080"
tcp_listen_addr = ":7030"

# db
db_dsn = "mongodb://localhost:27017"
database = "db_game"

# game evironment
registry = "consul"
transport = "tcp"
broker = "nsq"
