# config.toml

title = "yokai_game_config"

debug = false

game_id = 1001
account_connect_max = 5000

# ip and port
public_ip = "47.240.56.22"
https_listen_addr = ":443"
tcp_listen_addr = ":7030"

# tls_debug
cert_path_debug = "../../config/cert/localhost.crt"
key_path_debug = "../../config/cert/localhost.key"

# tls_release
cert_path_release = "../../config/cert/hellodudu.crt"
key_path_release = "../../config/cert/hellodudu.key"

# db
db_dsn = "mongodb://localhost:27017"
database = "db_game"

# game evironment
registry = "consul"
broker = "nsq"
