# config.toml

title = "yokai_game_config"

game_id = 1001
client_connect_max = 5000
client_timeout = "20s"
mysql_dsn = "root:123456@(mysql:3306)/db_game"
http_listen_addr = ":8080"
tcp_listen_addr = ":7030"

# game evironment
micro_registry = "mdns"
micro_transport = "tcp"
micro_broker = "http"
micro_server_id = 1001
